Suggestions enhancement
appbaseio/playground pull request #129
Opened 2023-08-14 10:50 UTC by SavvyShah

- Document suggestions story

2023-09-04 04:49 UTC, mohdashraf010897 requested changes
Please see the review comments

2023-09-04 04:49 UTC, mohdashraf010897 commented on stories/index.js
> +  .add(
@SavvyShah duplicate story

2023-09-04 04:49 UTC, mohdashraf010897 commented on stories/index.js
Please check the additions, the PR should just add the relevant stories for document suggestions just after the 'faqsuggestions'(or which ever was added last) related stories, the intention is to maintain chronological order.

2023-09-04 04:49 UTC, mohdashraf010897 commented on stories/reactivesearch/SearchBox.stories.js
> +							showDistinctSuggestions
@SavvyShah  is this required by default to be `true`?

2023-09-04 04:49 UTC, mohdashraf010897 commented on stories/reactivesearch/SearchBoxWithDocumentSuggestions.stories.js
@SavvyShah Can you explain the need for having a separate file for DocumentSuggestions? I would say we utilize the existing [SearchBoxDefault](https://github.com/appbaseio/playground/blob/feat/suggestions-enhancement/stories/reactivesearch/SearchBox.stories.js) file.

2023-09-04 04:49 UTC, mohdashraf010897 commented on stories/reactivesearch/movie-store.css
@SavvyShah Please help me understand the use of this css file.

2023-09-05 04:04 UTC, SavvyShah commented on stories/reactivesearch/SearchBoxWithDocumentSuggestions.stories.js
The `good-books-ds` index didn't have document suggestions. That's why I made a new file.

2023-09-05 06:21 UTC, SavvyShah commented on stories/index.js
> +  .add(
OK

2023-09-05 06:23 UTC, SavvyShah commented on stories/reactivesearch/SearchBox.stories.js
> +							showDistinctSuggestions
Yes. I'll remove it then.

2023-09-05 06:24 UTC, SavvyShah commented on stories/reactivesearch/movie-store.css
It's styling for the document suggestions file. It can be reused when we are using `movie-store` index.

2023-09-15 15:22 UTC, merged