Feat/image search
appbaseio/playground pull request #130
Opened 2023-09-15 15:06 UTC by SavvyShah

2023-10-03 04:02 UTC, mohdashraf010897 requested changes

2023-10-03 04:02 UTC, mohdashraf010897 commented on stories/index.js
> +        enableIndexSuggestions={boolean('enableIndexSuggestions', false)}
@SavvyShah Let's remove the `enableIndexSuggestions` knob as it seems not very relevant to the story

2023-10-03 04:02 UTC, mohdashraf010897 commented on stories/index.js
> +        renderItem={(suggestion)=>(<div>{suggestion._source.original_title} <span style={{color: "crimson", backgroundColor: "lightgray", padding: 5, borderRadius: 3}}>{new Date(Number(suggestion._so
@SavvyShah Let's have this hidden inside the SearchBoxDefault wrapper component to improve the readability. You can use a custom prop to switch the `renderITem` for documentsuggestions on/ off, a suggestion is `shouldCustomRenderDocumentSuggestion`

2023-10-03 04:02 UTC, mohdashraf010897 commented on stories/index.js
> +        renderItem={(suggestion)=>(<a style={{width:'100%', height: '100%', display: 'block', textDecoration: "none", color: "inherit"}} href={`https://www.google.com/search?q=${suggestion._source.or
@SavvyShah refer to the just previous comment

2023-10-10 10:10 UTC, SavvyShah commented on stories/index.js
> +        renderItem={(suggestion)=>(<div>{suggestion._source.original_title} <span style={{color: "crimson", backgroundColor: "lightgray", padding: 5, borderRadius: 3}}>{new Date(Number(suggestion._so
I've moved them in a utils folder.

2023-10-10 10:10 UTC, SavvyShah commented on stories/index.js
> +        renderItem={(suggestion)=>(<a style={{width:'100%', height: '100%', display: 'block', textDecoration: "none", color: "inherit"}} href={`https://www.google.com/search?q=${suggestion._source.or
I've moved them in a utils folder.

2023-10-10 10:10 UTC, SavvyShah commented on stories/index.js
> +        enableIndexSuggestions={boolean('enableIndexSuggestions', false)}
It's somewhat relevant for document suggestions, if we want to hide index suggestions when we already have some document suggestions. The change is not a new change although it appears in green.

2023-10-18 10:18 UTC, merged