Add story for scrollTarget
appbaseio/playground pull request #39
Opened 2018-09-24 13:06 UTC by jyash97

2018-09-24 15:31 UTC, metagrover requested changes

2018-09-24 15:31 UTC, metagrover commented on stories/reactivesearch/ReactiveList.stories.js
> +		const scrollStyle = this.props.scrollTargetStory ? ({
You will need to destructure other props now. `this.props.scrollTargetStory` is getting passed to `ReactiveList` on Line 38.

2018-09-25 07:28 UTC, metagrover approved these changes

2018-09-25 07:31 UTC, jyash97 commented
@metagrover Should I remove `yarn.lock` file from this ?

2018-09-25 07:33 UTC, metagrover commented
Does this lock file fix the deployment issue, where we needed to upgrade
the storybook?

On Tue, Sep 25, 2018, 1:01 PM Yash Joshi <notifications@github.com> wrote:

> @metagrover <https://github.com/metagrover> Should I remove yarn.lock
> file from this ?
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/appbaseio/playground/pull/39#issuecomment-424236998>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AIsZiskS4F-FOkUAniLb_rI3Br4hU14jks5uedvSgaJpZM4W2ni_>
> .
>

2018-09-25 07:37 UTC, jyash97 commented
Not sure, I just made this changes with playground cloned repo. Should I try deploying this ?

2018-09-27 14:39 UTC, merged